mkdir "2\build_n"
copy "build_n\celt0.0.7.0.dll" "2\build_n\"
mkdir "2\build_n"
copy "build_n\mumble-g15-helper.exe" "2\build_n\"
mkdir "2\build_n"
copy "build_n\mumble.exe" "2\build_n\"
mkdir "2\build_n"
copy "build_n\mumble_app.dll" "2\build_n\"
mkdir "2\build_n"
copy "build_n\mumble_ol.dll" "2\build_n\"
mkdir "2\build_n"
copy "build_n\mumble_ol_helper.exe" "2\build_n\"
mkdir "2\build_n"
copy "build_n\mumble_ol_helper_x64.exe" "2\build_n\"
mkdir "2\build_n"
copy "build_n\mumble_ol_x64.dll" "2\build_n\"
mkdir "2\build_n"
copy "build_n\opus.dll" "2\build_n\"
mkdir "2\build_n"
copy "build_n\rnnoise.dll" "2\build_n\"
mkdir "2\build_n"
copy "build_n\speex.dll" "2\build_n\"
mkdir "2\build_n\licenses"
copy "build_n\licenses\gpl.txt" "2\build_n\licenses\"
mkdir "2\build_n\licenses"
copy "build_n\licenses\lgpl.txt" "2\build_n\licenses\"
mkdir "2\build_n\licenses"
copy "build_n\licenses\Mumble.rtf" "2\build_n\licenses\"
mkdir "2\build_n\licenses"
copy "build_n\licenses\portaudio.txt" "2\build_n\licenses\"
mkdir "2\build_n\licenses"
copy "build_n\licenses\qt.txt" "2\build_n\licenses\"
mkdir "2\build_n\licenses"
copy "build_n\licenses\speex.txt" "2\build_n\licenses\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\amongus.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\aoc.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\arma2.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\bf1.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\bf1942.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\bf2.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\bf2142.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\bf3.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\bf4.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\bf4_x86.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\bfbc2.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\bfheroes.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\blacklight.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\borderlands.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\borderlands2.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\breach.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\cod2.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\cod4.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\cod5.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\codmw2.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\codmw2so.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\cs.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\dys.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\etqw.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\ffxiv.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\ffxiv_x64.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\gmod.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\gtaiv.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\gtasa.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\gtav.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\gw.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\insurgency.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\jc2.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\link.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\lol.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\lotro.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\ql.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\rl.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\se.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\sr.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\ut2004.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\ut3.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\ut99.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\wolfet.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\wow.dll" "2\build_n\plugins\"
mkdir "2\build_n\plugins"
copy "build_n\plugins\wow_x64.dll" "2\build_n\plugins\"
pause